### ISSUE TITLE
sample_images.zip

### ISSUE THREAD

**Issue by LurkerLuo** [javierganan99/gestures3D#1]
It will take too long to dowanload sample_images.zip. Can you send it to me by emai? My emai is 2684040253@qq.com. Thank you very much.

**Comment by javierganan99** [comment]
It is a 2.4 GB zip file. I can not send you the images directly by mail because the file is too large. The provided link in Google Drive contains the images. Do you have any problem with this link? In my case, it last less than 5 minutes to download all the demo images.

**Comment by LurkerLuo** [comment]
Thanks for your reply! It was my internet problem, and I've got it down now.
But I  coudn't download the pre-training model, can tou send them to me?

**Comment by javierganan99** [comment]
Sure! There is a problem with the model download. Thank you for notifying. Here is the gestures model in zip format:
[model_gestures.zip](https://github.com/javierganan99/gestures3D/files/11475314/model_gestures.zip)
The model for skeleton detection can be downloaded here: https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-w6-pose.pt

**Comment by LurkerLuo** [comment]
Now I can download them successfully! Thank you again for your great work!
