### ISSUE TITLE
Run gestures_predict.py

### ISSUE THREAD

**Issue by LKyra** [javierganan99/gestures3D#2]
I encountered some difficulties while trying to run “gestures_predict.py” using cuda:"RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper__native_batch_norm)"
I output “input.device” in "functional.py" and found that it uses CPU，while the others are CUDA.What should I do to make it run on Cuda?

**Comment by javierganan99** [comment]
Thank you for noticing! There was a line missed with **torch.no_grad()** in the gestures_predict.py script. I have updated it and now it works for me using the gpu. I am using the docker provided in the installation instructions. Let me know if it is solved for you.

**Comment by LKyra** [comment]
This works for me，thank you very much！But I have encountered some troubles again. In "skeleton. py", I will see "line 247, in plot_skeleton r, g, b = self.pose_ kpt_ color[kid] ValueError: too many values to unpack (expected 3) ". When I delete the relevant content before running, sometimes there will be a problem that the console outputs "done!" and then the program automatically exits.

**Comment by javierganan99** [comment]
Can you provide more information about the error in skeleton? I do not find the problem. The console outputs "Done!" when there are no more images to process. What do you mean by "when I delete the relevant content before running"?

**Comment by LKyra** [comment]
> 
I have resolved this issue and can now run the program normally! Thank you very much for your help!
